project_id = "gpyarcrizvjyukaazndj"

[auth]
enable_signup = true

[auth.email]
enable_signup = true
enable_confirmations = false
double_confirm_changes = false

[functions.auto-confirm-signup]
verify_jwt = false

[functions.register-user]
verify_jwt = false

[functions.admin-create-distributor]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false

