/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OurPackagesRouteImport } from './routes/our-packages'
import { Route as DistributorInfoRouteImport } from './routes/distributor-info'
import { Route as DistributorApplyRouteImport } from './routes/distributor-apply'
import { Route as DistributorRouteImport } from './routes/distributor'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DistributorIndexRouteImport } from './routes/distributor.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DistributorWithdrawRouteImport } from './routes/distributor.withdraw'
import { Route as DistributorUsersRouteImport } from './routes/distributor.users'
import { Route as DistributorSupportRouteImport } from './routes/distributor.support'
import { Route as DistributorProfileRouteImport } from './routes/distributor.profile'
import { Route as DistributorEarningsRouteImport } from './routes/distributor.earnings'
import { Route as AdminWithdrawalsRouteImport } from './routes/admin.withdrawals'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTasksRouteImport } from './routes/admin.tasks'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminPackagesRouteImport } from './routes/admin.packages'
import { Route as AdminMonitorRouteImport } from './routes/admin.monitor'
import { Route as AdminDistributorsRouteImport } from './routes/admin.distributors'
import { Route as AdminCommunityRouteImport } from './routes/admin.community'
import { Route as AdminApprovalsRouteImport } from './routes/admin.approvals'
import { Route as AuthenticatedWithdrawRouteImport } from './routes/_authenticated/withdraw'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedReferralRouteImport } from './routes/_authenticated/referral'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPackagesRouteImport } from './routes/_authenticated/packages'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCommunityRouteImport } from './routes/_authenticated/community'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AdminUsersIndexRouteImport } from './routes/admin.users.index'
import { Route as AdminUsersIdRouteImport } from './routes/admin.users.$id'
import { Route as AuthenticatedPackagesIdRouteImport } from './routes/_authenticated/packages.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OurPackagesRoute = OurPackagesRouteImport.update({
  id: '/our-packages',
  path: '/our-packages',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributorInfoRoute = DistributorInfoRouteImport.update({
  id: '/distributor-info',
  path: '/distributor-info',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributorApplyRoute = DistributorApplyRouteImport.update({
  id: '/distributor-apply',
  path: '/distributor-apply',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributorRoute = DistributorRouteImport.update({
  id: '/distributor',
  path: '/distributor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributorIndexRoute = DistributorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DistributorRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DistributorWithdrawRoute = DistributorWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => DistributorRoute,
} as any)
const DistributorUsersRoute = DistributorUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DistributorRoute,
} as any)
const DistributorSupportRoute = DistributorSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => DistributorRoute,
} as any)
const DistributorProfileRoute = DistributorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DistributorRoute,
} as any)
const DistributorEarningsRoute = DistributorEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => DistributorRoute,
} as any)
const AdminWithdrawalsRoute = AdminWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTasksRoute = AdminTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPackagesRoute = AdminPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMonitorRoute = AdminMonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDistributorsRoute = AdminDistributorsRouteImport.update({
  id: '/distributors',
  path: '/distributors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunityRoute = AdminCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedWithdrawRoute = AuthenticatedWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferralRoute = AuthenticatedReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPackagesRoute = AuthenticatedPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunityRoute = AuthenticatedCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AuthenticatedPackagesIdRoute = AuthenticatedPackagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedPackagesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/distributor': typeof DistributorRouteWithChildren
  '/distributor-apply': typeof DistributorApplyRoute
  '/distributor-info': typeof DistributorInfoRoute
  '/our-packages': typeof OurPackagesRoute
  '/register': typeof RegisterRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/packages': typeof AuthenticatedPackagesRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/referral': typeof AuthenticatedReferralRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/community': typeof AdminCommunityRoute
  '/admin/distributors': typeof AdminDistributorsRoute
  '/admin/monitor': typeof AdminMonitorRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/distributor/earnings': typeof DistributorEarningsRoute
  '/distributor/profile': typeof DistributorProfileRoute
  '/distributor/support': typeof DistributorSupportRoute
  '/distributor/users': typeof DistributorUsersRoute
  '/distributor/withdraw': typeof DistributorWithdrawRoute
  '/admin/': typeof AdminIndexRoute
  '/distributor/': typeof DistributorIndexRoute
  '/packages/$id': typeof AuthenticatedPackagesIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/distributor-apply': typeof DistributorApplyRoute
  '/distributor-info': typeof DistributorInfoRoute
  '/our-packages': typeof OurPackagesRoute
  '/register': typeof RegisterRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/packages': typeof AuthenticatedPackagesRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/referral': typeof AuthenticatedReferralRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/community': typeof AdminCommunityRoute
  '/admin/distributors': typeof AdminDistributorsRoute
  '/admin/monitor': typeof AdminMonitorRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/distributor/earnings': typeof DistributorEarningsRoute
  '/distributor/profile': typeof DistributorProfileRoute
  '/distributor/support': typeof DistributorSupportRoute
  '/distributor/users': typeof DistributorUsersRoute
  '/distributor/withdraw': typeof DistributorWithdrawRoute
  '/admin': typeof AdminIndexRoute
  '/distributor': typeof DistributorIndexRoute
  '/packages/$id': typeof AuthenticatedPackagesIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/distributor': typeof DistributorRouteWithChildren
  '/distributor-apply': typeof DistributorApplyRoute
  '/distributor-info': typeof DistributorInfoRoute
  '/our-packages': typeof OurPackagesRoute
  '/register': typeof RegisterRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/_authenticated/community': typeof AuthenticatedCommunityRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/packages': typeof AuthenticatedPackagesRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/referral': typeof AuthenticatedReferralRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/withdraw': typeof AuthenticatedWithdrawRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/community': typeof AdminCommunityRoute
  '/admin/distributors': typeof AdminDistributorsRoute
  '/admin/monitor': typeof AdminMonitorRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/distributor/earnings': typeof DistributorEarningsRoute
  '/distributor/profile': typeof DistributorProfileRoute
  '/distributor/support': typeof DistributorSupportRoute
  '/distributor/users': typeof DistributorUsersRoute
  '/distributor/withdraw': typeof DistributorWithdrawRoute
  '/admin/': typeof AdminIndexRoute
  '/distributor/': typeof DistributorIndexRoute
  '/_authenticated/packages/$id': typeof AuthenticatedPackagesIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/distributor'
    | '/distributor-apply'
    | '/distributor-info'
    | '/our-packages'
    | '/register'
    | '/checkout'
    | '/community'
    | '/dashboard'
    | '/packages'
    | '/profile'
    | '/referral'
    | '/tasks'
    | '/withdraw'
    | '/admin/approvals'
    | '/admin/community'
    | '/admin/distributors'
    | '/admin/monitor'
    | '/admin/packages'
    | '/admin/payments'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/tasks'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/distributor/earnings'
    | '/distributor/profile'
    | '/distributor/support'
    | '/distributor/users'
    | '/distributor/withdraw'
    | '/admin/'
    | '/distributor/'
    | '/packages/$id'
    | '/admin/users/$id'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/distributor-apply'
    | '/distributor-info'
    | '/our-packages'
    | '/register'
    | '/checkout'
    | '/community'
    | '/dashboard'
    | '/packages'
    | '/profile'
    | '/referral'
    | '/tasks'
    | '/withdraw'
    | '/admin/approvals'
    | '/admin/community'
    | '/admin/distributors'
    | '/admin/monitor'
    | '/admin/packages'
    | '/admin/payments'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/tasks'
    | '/admin/withdrawals'
    | '/distributor/earnings'
    | '/distributor/profile'
    | '/distributor/support'
    | '/distributor/users'
    | '/distributor/withdraw'
    | '/admin'
    | '/distributor'
    | '/packages/$id'
    | '/admin/users/$id'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/distributor'
    | '/distributor-apply'
    | '/distributor-info'
    | '/our-packages'
    | '/register'
    | '/_authenticated/checkout'
    | '/_authenticated/community'
    | '/_authenticated/dashboard'
    | '/_authenticated/packages'
    | '/_authenticated/profile'
    | '/_authenticated/referral'
    | '/_authenticated/tasks'
    | '/_authenticated/withdraw'
    | '/admin/approvals'
    | '/admin/community'
    | '/admin/distributors'
    | '/admin/monitor'
    | '/admin/packages'
    | '/admin/payments'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/tasks'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/distributor/earnings'
    | '/distributor/profile'
    | '/distributor/support'
    | '/distributor/users'
    | '/distributor/withdraw'
    | '/admin/'
    | '/distributor/'
    | '/_authenticated/packages/$id'
    | '/admin/users/$id'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  DistributorRoute: typeof DistributorRouteWithChildren
  DistributorApplyRoute: typeof DistributorApplyRoute
  DistributorInfoRoute: typeof DistributorInfoRoute
  OurPackagesRoute: typeof OurPackagesRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-packages': {
      id: '/our-packages'
      path: '/our-packages'
      fullPath: '/our-packages'
      preLoaderRoute: typeof OurPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distributor-info': {
      id: '/distributor-info'
      path: '/distributor-info'
      fullPath: '/distributor-info'
      preLoaderRoute: typeof DistributorInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distributor-apply': {
      id: '/distributor-apply'
      path: '/distributor-apply'
      fullPath: '/distributor-apply'
      preLoaderRoute: typeof DistributorApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distributor': {
      id: '/distributor'
      path: '/distributor'
      fullPath: '/distributor'
      preLoaderRoute: typeof DistributorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distributor/': {
      id: '/distributor/'
      path: '/'
      fullPath: '/distributor/'
      preLoaderRoute: typeof DistributorIndexRouteImport
      parentRoute: typeof DistributorRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/distributor/withdraw': {
      id: '/distributor/withdraw'
      path: '/withdraw'
      fullPath: '/distributor/withdraw'
      preLoaderRoute: typeof DistributorWithdrawRouteImport
      parentRoute: typeof DistributorRoute
    }
    '/distributor/users': {
      id: '/distributor/users'
      path: '/users'
      fullPath: '/distributor/users'
      preLoaderRoute: typeof DistributorUsersRouteImport
      parentRoute: typeof DistributorRoute
    }
    '/distributor/support': {
      id: '/distributor/support'
      path: '/support'
      fullPath: '/distributor/support'
      preLoaderRoute: typeof DistributorSupportRouteImport
      parentRoute: typeof DistributorRoute
    }
    '/distributor/profile': {
      id: '/distributor/profile'
      path: '/profile'
      fullPath: '/distributor/profile'
      preLoaderRoute: typeof DistributorProfileRouteImport
      parentRoute: typeof DistributorRoute
    }
    '/distributor/earnings': {
      id: '/distributor/earnings'
      path: '/earnings'
      fullPath: '/distributor/earnings'
      preLoaderRoute: typeof DistributorEarningsRouteImport
      parentRoute: typeof DistributorRoute
    }
    '/admin/withdrawals': {
      id: '/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AdminWithdrawalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tasks': {
      id: '/admin/tasks'
      path: '/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AdminTasksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/packages': {
      id: '/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminPackagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/monitor': {
      id: '/admin/monitor'
      path: '/monitor'
      fullPath: '/admin/monitor'
      preLoaderRoute: typeof AdminMonitorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/distributors': {
      id: '/admin/distributors'
      path: '/distributors'
      fullPath: '/admin/distributors'
      preLoaderRoute: typeof AdminDistributorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/community': {
      id: '/admin/community'
      path: '/community'
      fullPath: '/admin/community'
      preLoaderRoute: typeof AdminCommunityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/withdraw': {
      id: '/_authenticated/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof AuthenticatedWithdrawRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referral': {
      id: '/_authenticated/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof AuthenticatedReferralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/packages': {
      id: '/_authenticated/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof AuthenticatedPackagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/community': {
      id: '/_authenticated/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AuthenticatedCommunityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/users/$id': {
      id: '/admin/users/$id'
      path: '/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/_authenticated/packages/$id': {
      id: '/_authenticated/packages/$id'
      path: '/$id'
      fullPath: '/packages/$id'
      preLoaderRoute: typeof AuthenticatedPackagesIdRouteImport
      parentRoute: typeof AuthenticatedPackagesRoute
    }
  }
}

interface AuthenticatedPackagesRouteChildren {
  AuthenticatedPackagesIdRoute: typeof AuthenticatedPackagesIdRoute
}

const AuthenticatedPackagesRouteChildren: AuthenticatedPackagesRouteChildren = {
  AuthenticatedPackagesIdRoute: AuthenticatedPackagesIdRoute,
}

const AuthenticatedPackagesRouteWithChildren =
  AuthenticatedPackagesRoute._addFileChildren(
    AuthenticatedPackagesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedCommunityRoute: typeof AuthenticatedCommunityRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPackagesRoute: typeof AuthenticatedPackagesRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReferralRoute: typeof AuthenticatedReferralRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedWithdrawRoute: typeof AuthenticatedWithdrawRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedCommunityRoute: AuthenticatedCommunityRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPackagesRoute: AuthenticatedPackagesRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReferralRoute: AuthenticatedReferralRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedWithdrawRoute: AuthenticatedWithdrawRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminUsersRouteChildren {
  AdminUsersIdRoute: typeof AdminUsersIdRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersIdRoute: AdminUsersIdRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminCommunityRoute: typeof AdminCommunityRoute
  AdminDistributorsRoute: typeof AdminDistributorsRoute
  AdminMonitorRoute: typeof AdminMonitorRoute
  AdminPackagesRoute: typeof AdminPackagesRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminTasksRoute: typeof AdminTasksRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminWithdrawalsRoute: typeof AdminWithdrawalsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminCommunityRoute: AdminCommunityRoute,
  AdminDistributorsRoute: AdminDistributorsRoute,
  AdminMonitorRoute: AdminMonitorRoute,
  AdminPackagesRoute: AdminPackagesRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminTasksRoute: AdminTasksRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminWithdrawalsRoute: AdminWithdrawalsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DistributorRouteChildren {
  DistributorEarningsRoute: typeof DistributorEarningsRoute
  DistributorProfileRoute: typeof DistributorProfileRoute
  DistributorSupportRoute: typeof DistributorSupportRoute
  DistributorUsersRoute: typeof DistributorUsersRoute
  DistributorWithdrawRoute: typeof DistributorWithdrawRoute
  DistributorIndexRoute: typeof DistributorIndexRoute
}

const DistributorRouteChildren: DistributorRouteChildren = {
  DistributorEarningsRoute: DistributorEarningsRoute,
  DistributorProfileRoute: DistributorProfileRoute,
  DistributorSupportRoute: DistributorSupportRoute,
  DistributorUsersRoute: DistributorUsersRoute,
  DistributorWithdrawRoute: DistributorWithdrawRoute,
  DistributorIndexRoute: DistributorIndexRoute,
}

const DistributorRouteWithChildren = DistributorRoute._addFileChildren(
  DistributorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  DistributorRoute: DistributorRouteWithChildren,
  DistributorApplyRoute: DistributorApplyRoute,
  DistributorInfoRoute: DistributorInfoRoute,
  OurPackagesRoute: OurPackagesRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
