/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DistributorRouteImport } from './routes/distributor'
import { Route as DistributorApplyRouteImport } from './routes/distributor-apply'
import { Route as DistributorInfoRouteImport } from './routes/distributor-info'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as InstallRouteImport } from './routes/install'
import { Route as OurPackagesRouteImport } from './routes/our-packages'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedCommunityRouteImport } from './routes/_authenticated/community'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPackagesRouteImport } from './routes/_authenticated/packages'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedReferralRouteImport } from './routes/_authenticated/referral'
import { Route as AuthenticatedShopRouteImport } from './routes/_authenticated/shop'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedThemeRouteImport } from './routes/_authenticated/theme'
import { Route as AuthenticatedWithdrawRouteImport } from './routes/_authenticated/withdraw'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAppInstallsRouteImport } from './routes/admin.app-installs'
import { Route as AdminApprovalsRouteImport } from './routes/admin.approvals'
import { Route as AdminBackupRouteImport } from './routes/admin.backup'
import { Route as AdminCommunityRouteImport } from './routes/admin.community'
import { Route as AdminDistributorsRouteImport } from './routes/admin.distributors'
import { Route as AdminMonitorRouteImport } from './routes/admin.monitor'
import { Route as AdminNoticesRouteImport } from './routes/admin.notices'
import { Route as AdminPackagesRouteImport } from './routes/admin.packages'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminShopRouteImport } from './routes/admin.shop'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminTasksRouteImport } from './routes/admin.tasks'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminWithdrawalsRouteImport } from './routes/admin.withdrawals'
import { Route as DistributorIndexRouteImport } from './routes/distributor.index'
import { Route as DistributorEarningsRouteImport } from './routes/distributor.earnings'
import { Route as DistributorLeadsRouteImport } from './routes/distributor.leads'
import { Route as DistributorPackageRouteImport } from './routes/distributor.package'
import { Route as DistributorProfileRouteImport } from './routes/distributor.profile'
import { Route as DistributorSupportRouteImport } from './routes/distributor.support'
import { Route as DistributorTasksRouteImport } from './routes/distributor.tasks'
import { Route as DistributorUsersRouteImport } from './routes/distributor.users'
import { Route as DistributorWithdrawRouteImport } from './routes/distributor.withdraw'
import { Route as DistributorWithdrawalsRouteImport } from './routes/distributor.withdrawals'
import { Route as AuthenticatedPackagesIdRouteImport } from './routes/_authenticated/packages.$id'
import { Route as AdminDistributorsIndexRouteImport } from './routes/admin.distributors.index'
import { Route as AdminDistributorsIdRouteImport } from './routes/admin.distributors.$id'
import { Route as AdminShopIndexRouteImport } from './routes/admin.shop.index'
import { Route as AdminShopOrdersRouteImport } from './routes/admin.shop.orders'
import { Route as AdminShopProductsRouteImport } from './routes/admin.shop.products'
import { Route as AdminTaskPackagePackageIdRouteImport } from './routes/admin.task-package.$packageId'
import { Route as AdminTasksIndexRouteImport } from './routes/admin.tasks.index'
import { Route as AdminTasksDailyReportRouteImport } from './routes/admin.tasks.daily-report'
import { Route as AdminTasksDistributorActivityRouteImport } from './routes/admin.tasks.distributor-activity'
import { Route as AdminUsersIndexRouteImport } from './routes/admin.users.index'
import { Route as AdminUsersIdRouteImport } from './routes/admin.users.$id'
import { Route as AdminWithdrawalsIndexRouteImport } from './routes/admin.withdrawals.index'
import { Route as AdminWithdrawalsDistributorApprovalsRouteImport } from './routes/admin.withdrawals.distributor-approvals'
import { Route as DistributorTaskPackagePackageIdRouteImport } from './routes/distributor.task-package.$packageId'
import { Route as ApiPublicHooksAutoTasksRouteImport } from './routes/api/public/hooks/auto-tasks'
import { Route as ApiPublicHooksDailyBackupRouteImport } from './routes/api/public/hooks/daily-backup'
import { Route as ApiPublicHooksHealthRouteImport } from './routes/api/public/hooks/health'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram.webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributorRoute = DistributorRouteImport.update({
  id: '/distributor',
  path: '/distributor',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributorApplyRoute = DistributorApplyRouteImport.update({
  id: '/distributor-apply',
  path: '/distributor-apply',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributorInfoRoute = DistributorInfoRouteImport.update({
  id: '/distributor-info',
  path: '/distributor-info',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const OurPackagesRoute = OurPackagesRouteImport.update({
  id: '/our-packages',
  path: '/our-packages',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunityRoute = AuthenticatedCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPackagesRoute = AuthenticatedPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferralRoute = AuthenticatedReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShopRoute = AuthenticatedShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedThemeRoute = AuthenticatedThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWithdrawRoute = AuthenticatedWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppInstallsRoute = AdminAppInstallsRouteImport.update({
  id: '/app-installs',
  path: '/app-installs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBackupRoute = AdminBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunityRoute = AdminCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDistributorsRoute = AdminDistributorsRouteImport.update({
  id: '/distributors',
  path: '/distributors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMonitorRoute = AdminMonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNoticesRoute = AdminNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPackagesRoute = AdminPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShopRoute = AdminShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTasksRoute = AdminTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWithdrawalsRoute = AdminWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => AdminRoute,
} as any)
const DistributorIndexRoute = DistributorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DistributorRoute,
} as any)
const DistributorEarningsRoute = DistributorEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => DistributorRoute,
} as any)
const DistributorLeadsRoute = DistributorLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DistributorRoute,
} as any)
const DistributorPackageRoute = DistributorPackageRouteImport.update({
  id: '/package',
  path: '/package',
  getParentRoute: () => DistributorRoute,
} as any)
const DistributorProfileRoute = DistributorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DistributorRoute,
} as any)
const DistributorSupportRoute = DistributorSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => DistributorRoute,
} as any)
const DistributorTasksRoute = DistributorTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => DistributorRoute,
} as any)
const DistributorUsersRoute = DistributorUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DistributorRoute,
} as any)
const DistributorWithdrawRoute = DistributorWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => DistributorRoute,
} as any)
const DistributorWithdrawalsRoute = DistributorWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => DistributorRoute,
} as any)
const AuthenticatedPackagesIdRoute = AuthenticatedPackagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedPackagesRoute,
} as any)
const AdminDistributorsIndexRoute = AdminDistributorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDistributorsRoute,
} as any)
const AdminDistributorsIdRoute = AdminDistributorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminDistributorsRoute,
} as any)
const AdminShopIndexRoute = AdminShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminShopRoute,
} as any)
const AdminShopOrdersRoute = AdminShopOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminShopRoute,
} as any)
const AdminShopProductsRoute = AdminShopProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminShopRoute,
} as any)
const AdminTaskPackagePackageIdRoute =
  AdminTaskPackagePackageIdRouteImport.update({
    id: '/task-package/$packageId',
    path: '/task-package/$packageId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminTasksIndexRoute = AdminTasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminTasksRoute,
} as any)
const AdminTasksDailyReportRoute = AdminTasksDailyReportRouteImport.update({
  id: '/daily-report',
  path: '/daily-report',
  getParentRoute: () => AdminTasksRoute,
} as any)
const AdminTasksDistributorActivityRoute =
  AdminTasksDistributorActivityRouteImport.update({
    id: '/distributor-activity',
    path: '/distributor-activity',
    getParentRoute: () => AdminTasksRoute,
  } as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminWithdrawalsIndexRoute = AdminWithdrawalsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminWithdrawalsRoute,
} as any)
const AdminWithdrawalsDistributorApprovalsRoute =
  AdminWithdrawalsDistributorApprovalsRouteImport.update({
    id: '/distributor-approvals',
    path: '/distributor-approvals',
    getParentRoute: () => AdminWithdrawalsRoute,
  } as any)
const DistributorTaskPackagePackageIdRoute =
  DistributorTaskPackagePackageIdRouteImport.update({
    id: '/task-package/$packageId',
    path: '/task-package/$packageId',
    getParentRoute: () => DistributorRoute,
  } as any)
const ApiPublicHooksAutoTasksRoute = ApiPublicHooksAutoTasksRouteImport.update({
  id: '/api/public/hooks/auto-tasks',
  path: '/api/public/hooks/auto-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDailyBackupRoute =
  ApiPublicHooksDailyBackupRouteImport.update({
    id: '/api/public/hooks/daily-backup',
    path: '/api/public/hooks/daily-backup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksHealthRoute = ApiPublicHooksHealthRouteImport.update({
  id: '/api/public/hooks/health',
  path: '/api/public/hooks/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/distributor': typeof DistributorRouteWithChildren
  '/distributor-apply': typeof DistributorApplyRoute
  '/distributor-info': typeof DistributorInfoRoute
  '/how-it-works': typeof HowItWorksRoute
  '/install': typeof InstallRoute
  '/our-packages': typeof OurPackagesRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/packages': typeof AuthenticatedPackagesRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/referral': typeof AuthenticatedReferralRoute
  '/shop': typeof AuthenticatedShopRoute
  '/support': typeof AuthenticatedSupportRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/theme': typeof AuthenticatedThemeRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
  '/admin/app-installs': typeof AdminAppInstallsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/community': typeof AdminCommunityRoute
  '/admin/distributors': typeof AdminDistributorsRouteWithChildren
  '/admin/monitor': typeof AdminMonitorRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shop': typeof AdminShopRouteWithChildren
  '/admin/support': typeof AdminSupportRoute
  '/admin/tasks': typeof AdminTasksRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/withdrawals': typeof AdminWithdrawalsRouteWithChildren
  '/distributor/earnings': typeof DistributorEarningsRoute
  '/distributor/leads': typeof DistributorLeadsRoute
  '/distributor/package': typeof DistributorPackageRoute
  '/distributor/profile': typeof DistributorProfileRoute
  '/distributor/support': typeof DistributorSupportRoute
  '/distributor/tasks': typeof DistributorTasksRoute
  '/distributor/users': typeof DistributorUsersRoute
  '/distributor/withdraw': typeof DistributorWithdrawRoute
  '/distributor/withdrawals': typeof DistributorWithdrawalsRoute
  '/admin/': typeof AdminIndexRoute
  '/distributor/': typeof DistributorIndexRoute
  '/packages/$id': typeof AuthenticatedPackagesIdRoute
  '/admin/distributors/$id': typeof AdminDistributorsIdRoute
  '/admin/shop/orders': typeof AdminShopOrdersRoute
  '/admin/shop/products': typeof AdminShopProductsRoute
  '/admin/task-package/$packageId': typeof AdminTaskPackagePackageIdRoute
  '/admin/tasks/daily-report': typeof AdminTasksDailyReportRoute
  '/admin/tasks/distributor-activity': typeof AdminTasksDistributorActivityRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/withdrawals/distributor-approvals': typeof AdminWithdrawalsDistributorApprovalsRoute
  '/distributor/task-package/$packageId': typeof DistributorTaskPackagePackageIdRoute
  '/admin/distributors/': typeof AdminDistributorsIndexRoute
  '/admin/shop/': typeof AdminShopIndexRoute
  '/admin/tasks/': typeof AdminTasksIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/withdrawals/': typeof AdminWithdrawalsIndexRoute
  '/api/public/hooks/auto-tasks': typeof ApiPublicHooksAutoTasksRoute
  '/api/public/hooks/daily-backup': typeof ApiPublicHooksDailyBackupRoute
  '/api/public/hooks/health': typeof ApiPublicHooksHealthRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/distributor-apply': typeof DistributorApplyRoute
  '/distributor-info': typeof DistributorInfoRoute
  '/how-it-works': typeof HowItWorksRoute
  '/install': typeof InstallRoute
  '/our-packages': typeof OurPackagesRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/packages': typeof AuthenticatedPackagesRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/referral': typeof AuthenticatedReferralRoute
  '/shop': typeof AuthenticatedShopRoute
  '/support': typeof AuthenticatedSupportRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/theme': typeof AuthenticatedThemeRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
  '/admin/app-installs': typeof AdminAppInstallsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/community': typeof AdminCommunityRoute
  '/admin/monitor': typeof AdminMonitorRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/distributor/earnings': typeof DistributorEarningsRoute
  '/distributor/leads': typeof DistributorLeadsRoute
  '/distributor/package': typeof DistributorPackageRoute
  '/distributor/profile': typeof DistributorProfileRoute
  '/distributor/support': typeof DistributorSupportRoute
  '/distributor/tasks': typeof DistributorTasksRoute
  '/distributor/users': typeof DistributorUsersRoute
  '/distributor/withdraw': typeof DistributorWithdrawRoute
  '/distributor/withdrawals': typeof DistributorWithdrawalsRoute
  '/admin': typeof AdminIndexRoute
  '/distributor': typeof DistributorIndexRoute
  '/packages/$id': typeof AuthenticatedPackagesIdRoute
  '/admin/distributors/$id': typeof AdminDistributorsIdRoute
  '/admin/shop/orders': typeof AdminShopOrdersRoute
  '/admin/shop/products': typeof AdminShopProductsRoute
  '/admin/task-package/$packageId': typeof AdminTaskPackagePackageIdRoute
  '/admin/tasks/daily-report': typeof AdminTasksDailyReportRoute
  '/admin/tasks/distributor-activity': typeof AdminTasksDistributorActivityRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/withdrawals/distributor-approvals': typeof AdminWithdrawalsDistributorApprovalsRoute
  '/distributor/task-package/$packageId': typeof DistributorTaskPackagePackageIdRoute
  '/admin/distributors': typeof AdminDistributorsIndexRoute
  '/admin/shop': typeof AdminShopIndexRoute
  '/admin/tasks': typeof AdminTasksIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/withdrawals': typeof AdminWithdrawalsIndexRoute
  '/api/public/hooks/auto-tasks': typeof ApiPublicHooksAutoTasksRoute
  '/api/public/hooks/daily-backup': typeof ApiPublicHooksDailyBackupRoute
  '/api/public/hooks/health': typeof ApiPublicHooksHealthRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/distributor': typeof DistributorRouteWithChildren
  '/distributor-apply': typeof DistributorApplyRoute
  '/distributor-info': typeof DistributorInfoRoute
  '/how-it-works': typeof HowItWorksRoute
  '/install': typeof InstallRoute
  '/our-packages': typeof OurPackagesRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/_authenticated/community': typeof AuthenticatedCommunityRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/packages': typeof AuthenticatedPackagesRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/referral': typeof AuthenticatedReferralRoute
  '/_authenticated/shop': typeof AuthenticatedShopRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/theme': typeof AuthenticatedThemeRoute
  '/_authenticated/withdraw': typeof AuthenticatedWithdrawRoute
  '/admin/app-installs': typeof AdminAppInstallsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/community': typeof AdminCommunityRoute
  '/admin/distributors': typeof AdminDistributorsRouteWithChildren
  '/admin/monitor': typeof AdminMonitorRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shop': typeof AdminShopRouteWithChildren
  '/admin/support': typeof AdminSupportRoute
  '/admin/tasks': typeof AdminTasksRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/withdrawals': typeof AdminWithdrawalsRouteWithChildren
  '/distributor/earnings': typeof DistributorEarningsRoute
  '/distributor/leads': typeof DistributorLeadsRoute
  '/distributor/package': typeof DistributorPackageRoute
  '/distributor/profile': typeof DistributorProfileRoute
  '/distributor/support': typeof DistributorSupportRoute
  '/distributor/tasks': typeof DistributorTasksRoute
  '/distributor/users': typeof DistributorUsersRoute
  '/distributor/withdraw': typeof DistributorWithdrawRoute
  '/distributor/withdrawals': typeof DistributorWithdrawalsRoute
  '/admin/': typeof AdminIndexRoute
  '/distributor/': typeof DistributorIndexRoute
  '/_authenticated/packages/$id': typeof AuthenticatedPackagesIdRoute
  '/admin/distributors/$id': typeof AdminDistributorsIdRoute
  '/admin/shop/orders': typeof AdminShopOrdersRoute
  '/admin/shop/products': typeof AdminShopProductsRoute
  '/admin/task-package/$packageId': typeof AdminTaskPackagePackageIdRoute
  '/admin/tasks/daily-report': typeof AdminTasksDailyReportRoute
  '/admin/tasks/distributor-activity': typeof AdminTasksDistributorActivityRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/withdrawals/distributor-approvals': typeof AdminWithdrawalsDistributorApprovalsRoute
  '/distributor/task-package/$packageId': typeof DistributorTaskPackagePackageIdRoute
  '/admin/distributors/': typeof AdminDistributorsIndexRoute
  '/admin/shop/': typeof AdminShopIndexRoute
  '/admin/tasks/': typeof AdminTasksIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/withdrawals/': typeof AdminWithdrawalsIndexRoute
  '/api/public/hooks/auto-tasks': typeof ApiPublicHooksAutoTasksRoute
  '/api/public/hooks/daily-backup': typeof ApiPublicHooksDailyBackupRoute
  '/api/public/hooks/health': typeof ApiPublicHooksHealthRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/distributor'
    | '/distributor-apply'
    | '/distributor-info'
    | '/how-it-works'
    | '/install'
    | '/our-packages'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/checkout'
    | '/community'
    | '/dashboard'
    | '/packages'
    | '/profile'
    | '/referral'
    | '/shop'
    | '/support'
    | '/tasks'
    | '/theme'
    | '/withdraw'
    | '/admin/app-installs'
    | '/admin/approvals'
    | '/admin/backup'
    | '/admin/community'
    | '/admin/distributors'
    | '/admin/monitor'
    | '/admin/notices'
    | '/admin/packages'
    | '/admin/payments'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/shop'
    | '/admin/support'
    | '/admin/tasks'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/distributor/earnings'
    | '/distributor/leads'
    | '/distributor/package'
    | '/distributor/profile'
    | '/distributor/support'
    | '/distributor/tasks'
    | '/distributor/users'
    | '/distributor/withdraw'
    | '/distributor/withdrawals'
    | '/admin/'
    | '/distributor/'
    | '/packages/$id'
    | '/admin/distributors/$id'
    | '/admin/shop/orders'
    | '/admin/shop/products'
    | '/admin/task-package/$packageId'
    | '/admin/tasks/daily-report'
    | '/admin/tasks/distributor-activity'
    | '/admin/users/$id'
    | '/admin/withdrawals/distributor-approvals'
    | '/distributor/task-package/$packageId'
    | '/admin/distributors/'
    | '/admin/shop/'
    | '/admin/tasks/'
    | '/admin/users/'
    | '/admin/withdrawals/'
    | '/api/public/hooks/auto-tasks'
    | '/api/public/hooks/daily-backup'
    | '/api/public/hooks/health'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/distributor-apply'
    | '/distributor-info'
    | '/how-it-works'
    | '/install'
    | '/our-packages'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/checkout'
    | '/community'
    | '/dashboard'
    | '/packages'
    | '/profile'
    | '/referral'
    | '/shop'
    | '/support'
    | '/tasks'
    | '/theme'
    | '/withdraw'
    | '/admin/app-installs'
    | '/admin/approvals'
    | '/admin/backup'
    | '/admin/community'
    | '/admin/monitor'
    | '/admin/notices'
    | '/admin/packages'
    | '/admin/payments'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/support'
    | '/distributor/earnings'
    | '/distributor/leads'
    | '/distributor/package'
    | '/distributor/profile'
    | '/distributor/support'
    | '/distributor/tasks'
    | '/distributor/users'
    | '/distributor/withdraw'
    | '/distributor/withdrawals'
    | '/admin'
    | '/distributor'
    | '/packages/$id'
    | '/admin/distributors/$id'
    | '/admin/shop/orders'
    | '/admin/shop/products'
    | '/admin/task-package/$packageId'
    | '/admin/tasks/daily-report'
    | '/admin/tasks/distributor-activity'
    | '/admin/users/$id'
    | '/admin/withdrawals/distributor-approvals'
    | '/distributor/task-package/$packageId'
    | '/admin/distributors'
    | '/admin/shop'
    | '/admin/tasks'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/api/public/hooks/auto-tasks'
    | '/api/public/hooks/daily-backup'
    | '/api/public/hooks/health'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/distributor'
    | '/distributor-apply'
    | '/distributor-info'
    | '/how-it-works'
    | '/install'
    | '/our-packages'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/_authenticated/checkout'
    | '/_authenticated/community'
    | '/_authenticated/dashboard'
    | '/_authenticated/packages'
    | '/_authenticated/profile'
    | '/_authenticated/referral'
    | '/_authenticated/shop'
    | '/_authenticated/support'
    | '/_authenticated/tasks'
    | '/_authenticated/theme'
    | '/_authenticated/withdraw'
    | '/admin/app-installs'
    | '/admin/approvals'
    | '/admin/backup'
    | '/admin/community'
    | '/admin/distributors'
    | '/admin/monitor'
    | '/admin/notices'
    | '/admin/packages'
    | '/admin/payments'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/shop'
    | '/admin/support'
    | '/admin/tasks'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/distributor/earnings'
    | '/distributor/leads'
    | '/distributor/package'
    | '/distributor/profile'
    | '/distributor/support'
    | '/distributor/tasks'
    | '/distributor/users'
    | '/distributor/withdraw'
    | '/distributor/withdrawals'
    | '/admin/'
    | '/distributor/'
    | '/_authenticated/packages/$id'
    | '/admin/distributors/$id'
    | '/admin/shop/orders'
    | '/admin/shop/products'
    | '/admin/task-package/$packageId'
    | '/admin/tasks/daily-report'
    | '/admin/tasks/distributor-activity'
    | '/admin/users/$id'
    | '/admin/withdrawals/distributor-approvals'
    | '/distributor/task-package/$packageId'
    | '/admin/distributors/'
    | '/admin/shop/'
    | '/admin/tasks/'
    | '/admin/users/'
    | '/admin/withdrawals/'
    | '/api/public/hooks/auto-tasks'
    | '/api/public/hooks/daily-backup'
    | '/api/public/hooks/health'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  DistributorRoute: typeof DistributorRouteWithChildren
  DistributorApplyRoute: typeof DistributorApplyRoute
  DistributorInfoRoute: typeof DistributorInfoRoute
  HowItWorksRoute: typeof HowItWorksRoute
  InstallRoute: typeof InstallRoute
  OurPackagesRoute: typeof OurPackagesRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  TermsRoute: typeof TermsRoute
  ApiPublicHooksAutoTasksRoute: typeof ApiPublicHooksAutoTasksRoute
  ApiPublicHooksDailyBackupRoute: typeof ApiPublicHooksDailyBackupRoute
  ApiPublicHooksHealthRoute: typeof ApiPublicHooksHealthRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distributor': {
      id: '/distributor'
      path: '/distributor'
      fullPath: '/distributor'
      preLoaderRoute: typeof DistributorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distributor-apply': {
      id: '/distributor-apply'
      path: '/distributor-apply'
      fullPath: '/distributor-apply'
      preLoaderRoute: typeof DistributorApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distributor-info': {
      id: '/distributor-info'
      path: '/distributor-info'
      fullPath: '/distributor-info'
      preLoaderRoute: typeof DistributorInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-packages': {
      id: '/our-packages'
      path: '/our-packages'
      fullPath: '/our-packages'
      preLoaderRoute: typeof OurPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/community': {
      id: '/_authenticated/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AuthenticatedCommunityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/packages': {
      id: '/_authenticated/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof AuthenticatedPackagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referral': {
      id: '/_authenticated/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof AuthenticatedReferralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shop': {
      id: '/_authenticated/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof AuthenticatedShopRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/theme': {
      id: '/_authenticated/theme'
      path: '/theme'
      fullPath: '/theme'
      preLoaderRoute: typeof AuthenticatedThemeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/withdraw': {
      id: '/_authenticated/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof AuthenticatedWithdrawRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/app-installs': {
      id: '/admin/app-installs'
      path: '/app-installs'
      fullPath: '/admin/app-installs'
      preLoaderRoute: typeof AdminAppInstallsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/backup': {
      id: '/admin/backup'
      path: '/backup'
      fullPath: '/admin/backup'
      preLoaderRoute: typeof AdminBackupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/community': {
      id: '/admin/community'
      path: '/community'
      fullPath: '/admin/community'
      preLoaderRoute: typeof AdminCommunityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/distributors': {
      id: '/admin/distributors'
      path: '/distributors'
      fullPath: '/admin/distributors'
      preLoaderRoute: typeof AdminDistributorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/monitor': {
      id: '/admin/monitor'
      path: '/monitor'
      fullPath: '/admin/monitor'
      preLoaderRoute: typeof AdminMonitorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notices': {
      id: '/admin/notices'
      path: '/notices'
      fullPath: '/admin/notices'
      preLoaderRoute: typeof AdminNoticesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/packages': {
      id: '/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminPackagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shop': {
      id: '/admin/shop'
      path: '/shop'
      fullPath: '/admin/shop'
      preLoaderRoute: typeof AdminShopRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tasks': {
      id: '/admin/tasks'
      path: '/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AdminTasksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/withdrawals': {
      id: '/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AdminWithdrawalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/distributor/': {
      id: '/distributor/'
      path: '/'
      fullPath: '/distributor/'
      preLoaderRoute: typeof DistributorIndexRouteImport
      parentRoute: typeof DistributorRoute
    }
    '/distributor/earnings': {
      id: '/distributor/earnings'
      path: '/earnings'
      fullPath: '/distributor/earnings'
      preLoaderRoute: typeof DistributorEarningsRouteImport
      parentRoute: typeof DistributorRoute
    }
    '/distributor/leads': {
      id: '/distributor/leads'
      path: '/leads'
      fullPath: '/distributor/leads'
      preLoaderRoute: typeof DistributorLeadsRouteImport
      parentRoute: typeof DistributorRoute
    }
    '/distributor/package': {
      id: '/distributor/package'
      path: '/package'
      fullPath: '/distributor/package'
      preLoaderRoute: typeof DistributorPackageRouteImport
      parentRoute: typeof DistributorRoute
    }
    '/distributor/profile': {
      id: '/distributor/profile'
      path: '/profile'
      fullPath: '/distributor/profile'
      preLoaderRoute: typeof DistributorProfileRouteImport
      parentRoute: typeof DistributorRoute
    }
    '/distributor/support': {
      id: '/distributor/support'
      path: '/support'
      fullPath: '/distributor/support'
      preLoaderRoute: typeof DistributorSupportRouteImport
      parentRoute: typeof DistributorRoute
    }
    '/distributor/tasks': {
      id: '/distributor/tasks'
      path: '/tasks'
      fullPath: '/distributor/tasks'
      preLoaderRoute: typeof DistributorTasksRouteImport
      parentRoute: typeof DistributorRoute
    }
    '/distributor/users': {
      id: '/distributor/users'
      path: '/users'
      fullPath: '/distributor/users'
      preLoaderRoute: typeof DistributorUsersRouteImport
      parentRoute: typeof DistributorRoute
    }
    '/distributor/withdraw': {
      id: '/distributor/withdraw'
      path: '/withdraw'
      fullPath: '/distributor/withdraw'
      preLoaderRoute: typeof DistributorWithdrawRouteImport
      parentRoute: typeof DistributorRoute
    }
    '/distributor/withdrawals': {
      id: '/distributor/withdrawals'
      path: '/withdrawals'
      fullPath: '/distributor/withdrawals'
      preLoaderRoute: typeof DistributorWithdrawalsRouteImport
      parentRoute: typeof DistributorRoute
    }
    '/_authenticated/packages/$id': {
      id: '/_authenticated/packages/$id'
      path: '/$id'
      fullPath: '/packages/$id'
      preLoaderRoute: typeof AuthenticatedPackagesIdRouteImport
      parentRoute: typeof AuthenticatedPackagesRoute
    }
    '/admin/distributors/': {
      id: '/admin/distributors/'
      path: '/'
      fullPath: '/admin/distributors/'
      preLoaderRoute: typeof AdminDistributorsIndexRouteImport
      parentRoute: typeof AdminDistributorsRoute
    }
    '/admin/distributors/$id': {
      id: '/admin/distributors/$id'
      path: '/$id'
      fullPath: '/admin/distributors/$id'
      preLoaderRoute: typeof AdminDistributorsIdRouteImport
      parentRoute: typeof AdminDistributorsRoute
    }
    '/admin/shop/': {
      id: '/admin/shop/'
      path: '/'
      fullPath: '/admin/shop/'
      preLoaderRoute: typeof AdminShopIndexRouteImport
      parentRoute: typeof AdminShopRoute
    }
    '/admin/shop/orders': {
      id: '/admin/shop/orders'
      path: '/orders'
      fullPath: '/admin/shop/orders'
      preLoaderRoute: typeof AdminShopOrdersRouteImport
      parentRoute: typeof AdminShopRoute
    }
    '/admin/shop/products': {
      id: '/admin/shop/products'
      path: '/products'
      fullPath: '/admin/shop/products'
      preLoaderRoute: typeof AdminShopProductsRouteImport
      parentRoute: typeof AdminShopRoute
    }
    '/admin/task-package/$packageId': {
      id: '/admin/task-package/$packageId'
      path: '/task-package/$packageId'
      fullPath: '/admin/task-package/$packageId'
      preLoaderRoute: typeof AdminTaskPackagePackageIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tasks/': {
      id: '/admin/tasks/'
      path: '/'
      fullPath: '/admin/tasks/'
      preLoaderRoute: typeof AdminTasksIndexRouteImport
      parentRoute: typeof AdminTasksRoute
    }
    '/admin/tasks/daily-report': {
      id: '/admin/tasks/daily-report'
      path: '/daily-report'
      fullPath: '/admin/tasks/daily-report'
      preLoaderRoute: typeof AdminTasksDailyReportRouteImport
      parentRoute: typeof AdminTasksRoute
    }
    '/admin/tasks/distributor-activity': {
      id: '/admin/tasks/distributor-activity'
      path: '/distributor-activity'
      fullPath: '/admin/tasks/distributor-activity'
      preLoaderRoute: typeof AdminTasksDistributorActivityRouteImport
      parentRoute: typeof AdminTasksRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/users/$id': {
      id: '/admin/users/$id'
      path: '/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/withdrawals/': {
      id: '/admin/withdrawals/'
      path: '/'
      fullPath: '/admin/withdrawals/'
      preLoaderRoute: typeof AdminWithdrawalsIndexRouteImport
      parentRoute: typeof AdminWithdrawalsRoute
    }
    '/admin/withdrawals/distributor-approvals': {
      id: '/admin/withdrawals/distributor-approvals'
      path: '/distributor-approvals'
      fullPath: '/admin/withdrawals/distributor-approvals'
      preLoaderRoute: typeof AdminWithdrawalsDistributorApprovalsRouteImport
      parentRoute: typeof AdminWithdrawalsRoute
    }
    '/distributor/task-package/$packageId': {
      id: '/distributor/task-package/$packageId'
      path: '/task-package/$packageId'
      fullPath: '/distributor/task-package/$packageId'
      preLoaderRoute: typeof DistributorTaskPackagePackageIdRouteImport
      parentRoute: typeof DistributorRoute
    }
    '/api/public/hooks/auto-tasks': {
      id: '/api/public/hooks/auto-tasks'
      path: '/api/public/hooks/auto-tasks'
      fullPath: '/api/public/hooks/auto-tasks'
      preLoaderRoute: typeof ApiPublicHooksAutoTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-backup': {
      id: '/api/public/hooks/daily-backup'
      path: '/api/public/hooks/daily-backup'
      fullPath: '/api/public/hooks/daily-backup'
      preLoaderRoute: typeof ApiPublicHooksDailyBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/health': {
      id: '/api/public/hooks/health'
      path: '/api/public/hooks/health'
      fullPath: '/api/public/hooks/health'
      preLoaderRoute: typeof ApiPublicHooksHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedPackagesRouteChildren {
  AuthenticatedPackagesIdRoute: typeof AuthenticatedPackagesIdRoute
}

const AuthenticatedPackagesRouteChildren: AuthenticatedPackagesRouteChildren = {
  AuthenticatedPackagesIdRoute: AuthenticatedPackagesIdRoute,
}

const AuthenticatedPackagesRouteWithChildren =
  AuthenticatedPackagesRoute._addFileChildren(
    AuthenticatedPackagesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedCommunityRoute: typeof AuthenticatedCommunityRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPackagesRoute: typeof AuthenticatedPackagesRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReferralRoute: typeof AuthenticatedReferralRoute
  AuthenticatedShopRoute: typeof AuthenticatedShopRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedThemeRoute: typeof AuthenticatedThemeRoute
  AuthenticatedWithdrawRoute: typeof AuthenticatedWithdrawRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedCommunityRoute: AuthenticatedCommunityRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPackagesRoute: AuthenticatedPackagesRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReferralRoute: AuthenticatedReferralRoute,
  AuthenticatedShopRoute: AuthenticatedShopRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedThemeRoute: AuthenticatedThemeRoute,
  AuthenticatedWithdrawRoute: AuthenticatedWithdrawRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminDistributorsRouteChildren {
  AdminDistributorsIdRoute: typeof AdminDistributorsIdRoute
  AdminDistributorsIndexRoute: typeof AdminDistributorsIndexRoute
}

const AdminDistributorsRouteChildren: AdminDistributorsRouteChildren = {
  AdminDistributorsIdRoute: AdminDistributorsIdRoute,
  AdminDistributorsIndexRoute: AdminDistributorsIndexRoute,
}

const AdminDistributorsRouteWithChildren =
  AdminDistributorsRoute._addFileChildren(AdminDistributorsRouteChildren)

interface AdminShopRouteChildren {
  AdminShopOrdersRoute: typeof AdminShopOrdersRoute
  AdminShopProductsRoute: typeof AdminShopProductsRoute
  AdminShopIndexRoute: typeof AdminShopIndexRoute
}

const AdminShopRouteChildren: AdminShopRouteChildren = {
  AdminShopOrdersRoute: AdminShopOrdersRoute,
  AdminShopProductsRoute: AdminShopProductsRoute,
  AdminShopIndexRoute: AdminShopIndexRoute,
}

const AdminShopRouteWithChildren = AdminShopRoute._addFileChildren(
  AdminShopRouteChildren,
)

interface AdminTasksRouteChildren {
  AdminTasksDailyReportRoute: typeof AdminTasksDailyReportRoute
  AdminTasksDistributorActivityRoute: typeof AdminTasksDistributorActivityRoute
  AdminTasksIndexRoute: typeof AdminTasksIndexRoute
}

const AdminTasksRouteChildren: AdminTasksRouteChildren = {
  AdminTasksDailyReportRoute: AdminTasksDailyReportRoute,
  AdminTasksDistributorActivityRoute: AdminTasksDistributorActivityRoute,
  AdminTasksIndexRoute: AdminTasksIndexRoute,
}

const AdminTasksRouteWithChildren = AdminTasksRoute._addFileChildren(
  AdminTasksRouteChildren,
)

interface AdminUsersRouteChildren {
  AdminUsersIdRoute: typeof AdminUsersIdRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersIdRoute: AdminUsersIdRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminWithdrawalsRouteChildren {
  AdminWithdrawalsDistributorApprovalsRoute: typeof AdminWithdrawalsDistributorApprovalsRoute
  AdminWithdrawalsIndexRoute: typeof AdminWithdrawalsIndexRoute
}

const AdminWithdrawalsRouteChildren: AdminWithdrawalsRouteChildren = {
  AdminWithdrawalsDistributorApprovalsRoute:
    AdminWithdrawalsDistributorApprovalsRoute,
  AdminWithdrawalsIndexRoute: AdminWithdrawalsIndexRoute,
}

const AdminWithdrawalsRouteWithChildren =
  AdminWithdrawalsRoute._addFileChildren(AdminWithdrawalsRouteChildren)

interface AdminRouteChildren {
  AdminAppInstallsRoute: typeof AdminAppInstallsRoute
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminBackupRoute: typeof AdminBackupRoute
  AdminCommunityRoute: typeof AdminCommunityRoute
  AdminDistributorsRoute: typeof AdminDistributorsRouteWithChildren
  AdminMonitorRoute: typeof AdminMonitorRoute
  AdminNoticesRoute: typeof AdminNoticesRoute
  AdminPackagesRoute: typeof AdminPackagesRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminShopRoute: typeof AdminShopRouteWithChildren
  AdminSupportRoute: typeof AdminSupportRoute
  AdminTasksRoute: typeof AdminTasksRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminWithdrawalsRoute: typeof AdminWithdrawalsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminTaskPackagePackageIdRoute: typeof AdminTaskPackagePackageIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAppInstallsRoute: AdminAppInstallsRoute,
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminBackupRoute: AdminBackupRoute,
  AdminCommunityRoute: AdminCommunityRoute,
  AdminDistributorsRoute: AdminDistributorsRouteWithChildren,
  AdminMonitorRoute: AdminMonitorRoute,
  AdminNoticesRoute: AdminNoticesRoute,
  AdminPackagesRoute: AdminPackagesRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminShopRoute: AdminShopRouteWithChildren,
  AdminSupportRoute: AdminSupportRoute,
  AdminTasksRoute: AdminTasksRouteWithChildren,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminWithdrawalsRoute: AdminWithdrawalsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminTaskPackagePackageIdRoute: AdminTaskPackagePackageIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DistributorRouteChildren {
  DistributorEarningsRoute: typeof DistributorEarningsRoute
  DistributorLeadsRoute: typeof DistributorLeadsRoute
  DistributorPackageRoute: typeof DistributorPackageRoute
  DistributorProfileRoute: typeof DistributorProfileRoute
  DistributorSupportRoute: typeof DistributorSupportRoute
  DistributorTasksRoute: typeof DistributorTasksRoute
  DistributorUsersRoute: typeof DistributorUsersRoute
  DistributorWithdrawRoute: typeof DistributorWithdrawRoute
  DistributorWithdrawalsRoute: typeof DistributorWithdrawalsRoute
  DistributorIndexRoute: typeof DistributorIndexRoute
  DistributorTaskPackagePackageIdRoute: typeof DistributorTaskPackagePackageIdRoute
}

const DistributorRouteChildren: DistributorRouteChildren = {
  DistributorEarningsRoute: DistributorEarningsRoute,
  DistributorLeadsRoute: DistributorLeadsRoute,
  DistributorPackageRoute: DistributorPackageRoute,
  DistributorProfileRoute: DistributorProfileRoute,
  DistributorSupportRoute: DistributorSupportRoute,
  DistributorTasksRoute: DistributorTasksRoute,
  DistributorUsersRoute: DistributorUsersRoute,
  DistributorWithdrawRoute: DistributorWithdrawRoute,
  DistributorWithdrawalsRoute: DistributorWithdrawalsRoute,
  DistributorIndexRoute: DistributorIndexRoute,
  DistributorTaskPackagePackageIdRoute: DistributorTaskPackagePackageIdRoute,
}

const DistributorRouteWithChildren = DistributorRoute._addFileChildren(
  DistributorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  DistributorRoute: DistributorRouteWithChildren,
  DistributorApplyRoute: DistributorApplyRoute,
  DistributorInfoRoute: DistributorInfoRoute,
  HowItWorksRoute: HowItWorksRoute,
  InstallRoute: InstallRoute,
  OurPackagesRoute: OurPackagesRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  TermsRoute: TermsRoute,
  ApiPublicHooksAutoTasksRoute: ApiPublicHooksAutoTasksRoute,
  ApiPublicHooksDailyBackupRoute: ApiPublicHooksDailyBackupRoute,
  ApiPublicHooksHealthRoute: ApiPublicHooksHealthRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
